services:
  - docker

matrix:
  fast_finish: true

before_script:
  - make build

script:
  - make test

after_success:
  - if [[ "${TRAVIS_TAG}" != "" ]]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag udovicic/varnish:4 udovicic/varnish:latest;
    docker tag udovicic/varnish:4 udovicic/varnish:${TRAVIS_TAG};
    docker push udovicic/varnish:4;
    docker push udovicic/varnish:latest;
    docker push udovicic/varnish:${TRAVIS_TAG};
    fi